// public_html/src/js/Components/Breadcrumb.vue
<template>
    <div id="breadcrumbs">
        <a href="/dashboard/#dashboard" class="breadcrumbs-home">
            <i class="fa fa-home fa-lg fa-fw"/>
        </a>
        <small><i class="fa fa-chevron-right fa-fw text-muted"/></small>
        {{ title }}
    </div>
</template>
<script type="text/babel">
    export default {
        name : 'breadcrumb',
        props : {
            title : {
                type : String,
                required : true
            }
        }
    }
</script>

// public_html/src/app/core/main/breadcrumb/breadcrumb.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'breadcrumb',
  templateUrl: './breadcrumb.component.html',
  styleUrls: ['./breadcrumb.component.css']
})
export class BreadcrumbComponent implements OnInit {

  public title: string = 'Dashboard';

  constructor() { }

  ngOnInit() {
  }

}

<div id="breadcrumbs">
  <a href="/dashboard/#dashboard" class="breadcrumbs-home">
    <i class="fa fa-home fa-lg fa-fw"></i>
  </a>
  <small><i class="fa fa-chevron-right fa-fw text-muted"></i></small>
  {{ title }}
</div>
